<a href="https://colab.research.google.com/github/Saichandan37/pytorch-projects/blob/main/NanoGpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
with open('Shakespeare.txt','r',encoding='utf-8') as f:
  text=f.read()
  print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [111]:
sampleset_chars=sorted(list(set(text)))
print(sampleset_chars,len(sampleset_chars))
vocab_size=len(sampleset_chars)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] 65


In [112]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [113]:
#My code - Char to Num
def cton(ch):
    print(ch)
    for t in list(enumerate(sampleset_chars)):
      if(ch==t[1]):
        return t[0]

char_to_num= lambda s:list([cton(ch) for ch in s])
char_to_num(text[:1000])

itos = { i:ch for i,ch in enumerate(sampleset_chars) }
decode = lambda l: ''.join([itos[i] for i in l])

# for sample_char in sample_chars
# char_to_num(text[:1000])


F
i
r
s
t
 
C
i
t
i
z
e
n
:


B
e
f
o
r
e
 
w
e
 
p
r
o
c
e
e
d
 
a
n
y
 
f
u
r
t
h
e
r
,
 
h
e
a
r
 
m
e
 
s
p
e
a
k
.




A
l
l
:


S
p
e
a
k
,
 
s
p
e
a
k
.




F
i
r
s
t
 
C
i
t
i
z
e
n
:


Y
o
u
 
a
r
e
 
a
l
l
 
r
e
s
o
l
v
e
d
 
r
a
t
h
e
r
 
t
o
 
d
i
e
 
t
h
a
n
 
t
o
 
f
a
m
i
s
h
?




A
l
l
:


R
e
s
o
l
v
e
d
.
 
r
e
s
o
l
v
e
d
.




F
i
r
s
t
 
C
i
t
i
z
e
n
:


F
i
r
s
t
,
 
y
o
u
 
k
n
o
w
 
C
a
i
u
s
 
M
a
r
c
i
u
s
 
i
s
 
c
h
i
e
f
 
e
n
e
m
y
 
t
o
 
t
h
e
 
p
e
o
p
l
e
.




A
l
l
:


W
e
 
k
n
o
w
'
t
,
 
w
e
 
k
n
o
w
'
t
.




F
i
r
s
t
 
C
i
t
i
z
e
n
:


L
e
t
 
u
s
 
k
i
l
l
 
h
i
m
,
 
a
n
d
 
w
e
'
l
l
 
h
a
v
e
 
c
o
r
n
 
a
t
 
o
u
r
 
o
w
n
 
p
r
i
c
e
.


I
s
'
t
 
a
 
v
e
r
d
i
c
t
?




A
l
l
:


N
o
 
m
o
r
e
 
t
a
l
k
i
n
g
 
o
n
'
t
;
 
l
e
t
 
i
t
 
b
e
 
d
o
n
e
:
 
a
w
a
y
,
 
a
w
a
y
!




S
e
c
o
n
d
 
C
i
t
i
z
e
n
:


O
n
e
 
w
o
r
d
,
 
g
o
o
d
 
c
i
t
i
z
e
n
s
.




F
i
r
s
t
 
C
i
t
i
z
e
n
:


W
e
 
a
r
e
 
a
c
c
o
u
n
t
e
d
 
p
o
o
r


In [114]:
import torch
data=torch.tensor(char_to_num(text),dtype=torch.long)
data[:100]

Streaming output truncated to the last 5000 lines.
 
u
n
d
e
r
 
h
i
m
,


A
n
d
 
r
i
d
e
 
u
p
o
n
 
t
h
e
i
r
 
b
a
c
k
s
;
 
h
e
 
t
r
o
d
 
t
h
e
 
w
a
t
e
r
,


W
h
o
s
e
 
e
n
m
i
t
y
 
h
e
 
f
l
u
n
g
 
a
s
i
d
e
,
 
a
n
d
 
b
r
e
a
s
t
e
d


T
h
e
 
s
u
r
g
e
 
m
o
s
t
 
s
w
o
l
n
 
t
h
a
t
 
m
e
t
 
h
i
m
;
 
h
i
s
 
b
o
l
d
 
h
e
a
d


'
B
o
v
e
 
t
h
e
 
c
o
n
t
e
n
t
i
o
u
s
 
w
a
v
e
s
 
h
e
 
k
e
p
t
,
 
a
n
d
 
o
a
r
'
d


H
i
m
s
e
l
f
 
w
i
t
h
 
h
i
s
 
g
o
o
d
 
a
r
m
s
 
i
n
 
l
u
s
t
y
 
s
t
r
o
k
e


T
o
 
t
h
e
 
s
h
o
r
e
,
 
t
h
a
t
 
o
'
e
r
 
h
i
s
 
w
a
v
e
-
w
o
r
n
 
b
a
s
i
s
 
b
o
w
'
d
,


A
s
 
s
t
o
o
p
i
n
g
 
t
o
 
r
e
l
i
e
v
e
 
h
i
m
:
 
I
 
n
o
t
 
d
o
u
b
t


H
e
 
c
a
m
e
 
a
l
i
v
e
 
t
o
 
l
a
n
d
.




A
L
O
N
S
O
:


N
o
,
 
n
o
,
 
h
e
'
s
 
g
o
n
e
.




S
E
B
A
S
T
I
A
N
:


S
i
r
,
 
y
o
u
 
m
a
y
 
t
h
a
n
k
 
y
o
u
r
s
e
l
f
 
f
o
r
 
t
h
i
s
 
g
r
e
a
t
 
l
o
s
s
,


T
h
a
t
 
w
o
u
l
d
 
n
o
t
 
b
l
e
s
s
 
o
u
r
 
E
u
r
o
p
e
 
w

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])

In [115]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [116]:
block_size=8

x_train= train_data[:block_size]
y_train=train_data[1:block_size+1]
for i in range(block_size):
  context= x_train[:i+1]
  target=y_train[i]
  print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [117]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y=x.to(device),y.to(device)
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        # print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----


In [118]:
import torch
import torch.nn as nn
from torch.nn import functional as F

n_embd=32
class BigramLanguageModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.token_embedded_table= nn.Embedding(vocab_size,n_embd)
    self.position_embedded_table=nn.Embedding(block_size,n_embd)
    self.lm_head=nn.Linear(n_embd,vocab_size)

  def forward(self,xb,yb=None):
    B,T=xb.shape
    tok_emd=self.token_embedded_table(xb)
    # Only consider the last block_size tokens for position embeddings
    pos_emd=self.position_embedded_table(torch.arange(T,device=device))
    # print(pos_emd.shape)
    x=tok_emd+pos_emd
    logits=self.lm_head(x)
    if yb == None:
      loss = None
    else:
      B,T,C=(logits.shape)
      logits=logits.view(B*T,C)
      yb=yb.view(B*T)

      loss=F.cross_entropy(logits,yb)
    return logits,loss



  def generate(self,xb,pred_n_tokens):
    # Add device argument to torch.zeros
    xb = xb.to(device)
    for _ in range(pred_n_tokens):
      # Crop xb to the last block_size tokens if it's longer
      xb_cropped = xb[:, -block_size:] if xb.shape[1] > block_size else xb
      logits,loss=self(xb_cropped)
      next_token=logits[:,-1,:]
      next_token = next_token - next_token.max(dim=-1, keepdim=True).values
      probs = F.softmax(next_token/1.0, dim=-1) # (B, C)
      probs = torch.nan_to_num(probs, nan=0.0)
      idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
      xb = torch.cat((xb, idx_next), dim=1) # (B, T+1)
    return xb

model=BigramLanguageModel().to(device)
pred,loss=model(xb,yb)
print(pred.shape)
print(loss)

# print(model.generate(torch.zeros((1,1),dtype=torch.long),pred_n_tokens=100).tolist())

torch.Size([32, 65])
tensor(4.6424, grad_fn=<NllLossBackward0>)


In [119]:
# idx = torch.zeros((4, 1), dtype=torch.long)
# out = model.generate(idx, pred_n_tokens=100)
# print(out.shape)

In [120]:
import torch
torch.zeros(1,1)

tensor([[0.]])

In [121]:
import torch.optim as optim
optimizer = optim.AdamW(model.parameters(),lr=1e-3)

In [122]:
batch_size=32

epochs=5000
xb,yb = get_batch('train')
for epoch in range(epochs):
  logits,loss=model(xb,yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

  print(loss.item())


4.517619609832764
4.491132736206055
4.464831829071045
4.438716888427734
4.412790775299072
4.387054920196533
4.361507415771484
4.33615255355835
4.310987949371338
4.286014556884766
4.261232376098633
4.236640453338623
4.212238788604736
4.188025951385498
4.164000988006592
4.140163898468018
4.116511821746826
4.093043804168701
4.069759368896484
4.046656608581543
4.023733615875244
4.000988483428955
3.9784204959869385
3.9560282230377197
3.933809280395508
3.911762237548828
3.8898849487304688
3.8681766986846924
3.846635580062866
3.825260639190674
3.804048538208008
3.78299880027771
3.7621102333068848
3.741381883621216
3.720811367034912
3.7003984451293945
3.680140256881714
3.660036563873291
3.6400866508483887
3.620288372039795
3.6006417274475098
3.5811455249786377
3.561798334121704
3.542599678039551
3.523547887802124
3.504643201828003
3.48588490486145
3.4672718048095703
3.448803424835205
3.430478811264038
3.4122984409332275
3.3942606449127197
3.3763656616210938
3.3586130142211914
3.341002225875854

In [124]:
content =(decode(model.generate(torch.zeros((1,1),dtype=torch.long,device=device),pred_n_tokens=500)[0].tolist()))
content

'\n\n\n\nand, akisougr nd Crougr Crougr kingrororougrougr hend Cgrougr akindrororo hugryougr hyororougry grorougry Cry kingry sakind angrougry Cr kind grougror Cror and nd Crorougroror kIShugr kind Crendror grorerougr Cro kind spugr Cry grorougrougry gror pugr hyougror Croro akirougry pr kingror kind yore hugrougr Cro Cr kindryougr gryougr akissoro Cr phyougrorougror ndroryo Cry y y Cr s Cr and Cy Crorougrougr kis kirorougrougrougrend hendr kiror phass gryor pugrIShy kir ndr and kingr Cror kingrorougr'